"use strict";
const $=id=>document.getElementById(id);
const el={enter:$("enter"),welcome:$("welcome"),dojo:$("dojo"),homeButton:$("homeButton"),noziImage:$("noziImage"),noziFallback:$("noziFallback"),winkBubble:$("winkBubble"),accessory:$("accessory"),welcomeMessage:$("welcomeMessage"),xp:$("xp"),streak:$("streak"),levelName:$("levelName"),levelIcon:$("levelIcon"),mission:$("mission"),noziMessage:$("noziMessage"),videoTitle:$("videoTitle"),videoNote:$("videoNote"),videoDuration:$("videoDuration"),videoChannel:$("videoChannel"),rewardText:$("rewardText"),missionEnergyIcon:$("missionEnergyIcon"),startTraining:$("startTraining"),changeTraining:$("changeTraining"),videoArea:$("videoArea"),videoFrame:$("videoFrame"),youtubeLink:$("youtubeLink"),timerText:$("timerText"),timerIcon:$("timerIcon"),complete:$("complete"),result:$("result"),calendar:$("calendar"),badges:$("badges"),petalLayer:$("petalLayer")};
const KEYS={xp:"kendoMamaXp",completed:"kendoMamaCompletedDates",choices:"kendoMamaDailyVideoChoices"};
let state={xp:readNumber(KEYS.xp,0),completed:readArray(KEYS.completed),choices:readObject(KEYS.choices),energy:null,video:null,reward:0,started:false,seconds:0,timer:null};
const energy={low:{icon:"🌱",reward:5,messages:["Oggi andiamo piano. Anche poco conta.","Il dojo ti accoglie nelle giornate lente."]},medium:{icon:"🌸",reward:10,messages:["Troviamo un ritmo gentile e continuo.","Un movimento alla volta: costruiamo costanza."]},high:{icon:"⚔️",reward:15,messages:["Energia alta, ascolto ancora più alto.","La forza è anche sapere quando rallentare."]}};
const levels=[{min:0,name:"Novizio",icon:"🌱",accessory:"🌱"},{min:30,name:"Kōhai",icon:"🍙",accessory:"🎀"},{min:80,name:"Senpai",icon:"🌸",accessory:"🌸"},{min:160,name:"Kendō Mama",icon:"🥋",accessory:"🥋"}];
const badgeDefs=[{icon:"🌱",name:"Primo passo",text:"Completa la prima quest.",ok:()=>state.completed.length>=1},{icon:"🍙",name:"Costanza gentile",text:"Completa tre quest.",ok:()=>state.completed.length>=3},{icon:"🌸",name:"Sette petali",text:"Completa sette quest.",ok:()=>state.completed.length>=7},{icon:"🔥",name:"Tre giorni sul tatami",text:"Raggiungi una serie di tre giorni.",ok:()=>streak()>=3},{icon:"✨",name:"Spirito luminoso",text:"Raggiungi 50 XP.",ok:()=>state.xp>=50},{icon:"🥋",name:"Kendō Mama",text:"Raggiungi il livello finale.",ok:()=>state.xp>=160}];
init();
function init(){setupNozi();setupEvents();updateWelcome();updateProgress();scheduleWink()}
function setupNozi(){const fallback=()=>{el.noziImage.classList.add("hidden");el.noziFallback.classList.remove("hidden")};el.noziImage.addEventListener("error",fallback);if(el.noziImage.complete&&el.noziImage.naturalWidth===0)fallback()}
function setupEvents(){el.enter.addEventListener("click",()=>{el.welcome.classList.add("hidden");el.dojo.classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"})});el.homeButton.addEventListener("click",()=>{stopTimer();el.videoFrame.src="";el.dojo.classList.add("hidden");el.welcome.classList.remove("hidden")});document.querySelectorAll(".energy button").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".energy button").forEach(b=>b.classList.remove("selected"));button.classList.add("selected");chooseEnergy(button.dataset.energy)}));el.startTraining.addEventListener("click",beginTraining);el.changeTraining.addEventListener("click",nextVideo);el.complete.addEventListener("click",completeQuest)}
function chooseEnergy(kind){if(!videoLibrary[kind])return;state.energy=kind;state.reward=energy[kind].reward;state.video=dailyVideo(kind);state.started=false;resetMission();renderMission();el.mission.classList.remove("hidden");setTimeout(()=>el.mission.scrollIntoView({behavior:"smooth",block:"start"}),100)}
function dailyVideo(kind){const key=`${dateKey(new Date())}-${kind}`,list=videoLibrary[kind],saved=list.find(v=>v.id===state.choices[key]);if(saved)return saved;const selected=list[hash(key)%list.length];state.choices[key]=selected.id;save(KEYS.choices,state.choices);return selected}
function nextVideo(){if(!state.energy||!state.video)return;const list=videoLibrary[state.energy],index=list.findIndex(v=>v.id===state.video.id);state.video=list[(index+1)%list.length];state.choices[`${dateKey(new Date())}-${state.energy}`]=state.video.id;save(KEYS.choices,state.choices);state.started=false;resetMission();renderMission()}
function renderMission(){const cfg=energy[state.energy];el.videoTitle.textContent=state.video.title;el.videoNote.textContent=state.video.note;el.videoDuration.textContent=`${state.video.duration} minuti`;el.videoChannel.textContent=state.video.channel;el.rewardText.textContent=`+${state.reward} XP`;el.missionEnergyIcon.textContent=cfg.icon;el.noziMessage.textContent=random(cfg.messages);el.youtubeLink.href=`https://www.youtube.com/watch?v=${state.video.id}`;el.result.classList.add("hidden");syncCompletionButton()}
function resetMission(){stopTimer();state.seconds=0;el.videoArea.classList.add("hidden");el.complete.classList.add("hidden");el.startTraining.disabled=false;el.startTraining.textContent="▶️ Inizia allenamento";el.timerText.textContent="Video non ancora avviato";el.timerIcon.textContent="⏱️";el.videoFrame.src=""}
function beginTraining(){if(!state.video)return;state.started=true;el.videoFrame.src=`https://www.youtube-nocookie.com/embed/${state.video.id}?autoplay=1&rel=0`;el.videoArea.classList.remove("hidden");el.complete.classList.remove("hidden");el.startTraining.disabled=true;el.startTraining.textContent="Allenamento avviato 🌸";el.timerIcon.textContent="🥋";startTimer();syncCompletionButton()}
function completeQuest(){if(!state.started||!state.video)return;const today=dateKey(new Date());if(state.completed.includes(today)){el.result.textContent="La quest di oggi è già registrata. Puoi comunque ripetere l’allenamento. 🌸";el.result.classList.remove("hidden");syncCompletionButton();return}state.xp+=state.reward;state.completed=[...new Set([...state.completed,today])].sort();localStorage.setItem(KEYS.xp,String(state.xp));save(KEYS.completed,state.completed);stopTimer();updateProgress();updateWelcome();petals();el.result.innerHTML=`Quest completata! Hai guadagnato <strong>${state.reward} XP</strong>.<br>Nozi è fiera di te. 🍙🌸`;el.result.classList.remove("hidden");syncCompletionButton()}
function syncCompletionButton(){if(!state.energy)return;const done=state.completed.includes(dateKey(new Date()));el.complete.disabled=done;el.complete.textContent=done?"Quest già registrata ✓":"Quest completata"}
function updateProgress(){el.xp.textContent=state.xp;el.streak.textContent=streak();const level=[...levels].reverse().find(l=>state.xp>=l.min)||levels[0];el.levelName.textContent=level.name;el.levelIcon.textContent=level.icon;el.accessory.textContent=level.accessory;renderCalendar();renderBadges();syncCompletionButton()}
function updateWelcome(){const today=dateKey(new Date()),y=new Date();y.setDate(y.getDate()-1);if(!state.completed.length)el.welcomeMessage.innerHTML="Non serve essere perfetta.<br>Basta presentarsi sul tatami.";else if(state.completed.includes(today))el.welcomeMessage.innerHTML="Oggi sei già salita sul tatami.<br>Puoi tornare quando vuoi. 🌸";else if(state.completed.includes(dateKey(y)))el.welcomeMessage.innerHTML="Bentornata! Ieri ti sei allenata.<br>Continuiamo con gentilezza?";else el.welcomeMessage.innerHTML="Il dojo si è ricordato di te.<br>Anche cinque minuti vanno bene."}
function renderCalendar(){el.calendar.innerHTML="";const names=["Dom","Lun","Mar","Mer","Gio","Ven","Sab"],today=new Date(),todayKey=dateKey(today);for(let offset=6;offset>=0;offset--){const d=new Date(today);d.setHours(12,0,0,0);d.setDate(today.getDate()-offset);const key=dateKey(d),day=document.createElement("div");day.className="calendar-day";if(state.completed.includes(key))day.classList.add("completed");if(key===todayKey)day.classList.add("today");day.innerHTML=`<span class="calendar-name">${names[d.getDay()]}</span><strong>${d.getDate()}</strong><span>${state.completed.includes(key)?"🌸":"·"}</span>`;el.calendar.appendChild(day)}}
function renderBadges(){el.badges.innerHTML="";badgeDefs.forEach(b=>{const ok=b.ok(),card=document.createElement("div");card.className=`badge${ok?"":" locked"}`;card.innerHTML=`<span class="badge-icon">${ok?b.icon:"🔒"}</span><div><strong>${b.name}</strong><br><small>${b.text}</small></div>`;el.badges.appendChild(card)})}
function streak(){if(!state.completed.length)return 0;const set=new Set(state.completed),today=new Date();today.setHours(12,0,0,0);let cursor=set.has(dateKey(today))?new Date(today):new Date(today.setDate(today.getDate()-1));if(!set.has(dateKey(cursor)))return 0;let count=0;while(set.has(dateKey(cursor))){count++;cursor.setDate(cursor.getDate()-1)}return count}
function startTimer(){stopTimer();state.seconds=0;updateTimer();state.timer=setInterval(()=>{state.seconds++;updateTimer()},1000)}function stopTimer(){if(state.timer!==null){clearInterval(state.timer);state.timer=null}}function updateTimer(){const m=Math.floor(state.seconds/60),s=String(state.seconds%60).padStart(2,"0");el.timerText.textContent=`In corso • ${m}:${s}`}
function petals(){for(let i=0;i<24;i++){const p=document.createElement("span");p.className="petal";p.textContent=random(["🌸","🌸","✨"]);p.style.left=`${rand(0,100)}vw`;p.style.setProperty("--drift",`${rand(-100,100)}px`);p.style.animationDuration=`${rand(2800,4800)}ms`;p.style.animationDelay=`${rand(0,900)}ms`;el.petalLayer.appendChild(p);setTimeout(()=>p.remove(),6000)}}
function scheduleWink(){setTimeout(()=>{el.winkBubble.classList.remove("show");void el.winkBubble.offsetWidth;el.winkBubble.classList.add("show");scheduleWink()},rand(9000,16000))}
function dateKey(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`}function random(items){return items[Math.floor(Math.random()*items.length)]}function rand(min,max){return Math.floor(Math.random()*(max-min+1))+min}function hash(value){let h=0;for(let i=0;i<value.length;i++){h=((h<<5)-h)+value.charCodeAt(i);h|=0}return Math.abs(h)}function readNumber(key,fallback){const n=Number(localStorage.getItem(key));return Number.isFinite(n)?n:fallback}function readArray(key){try{const v=JSON.parse(localStorage.getItem(key));return Array.isArray(v)?v:[]}catch{return[]}}function readObject(key){try{const v=JSON.parse(localStorage.getItem(key));return v&&typeof v==="object"&&!Array.isArray(v)?v:{}}catch{return{}}}function save(key,value){localStorage.setItem(key,JSON.stringify(value))}
